/* eslint-disable import/order */

import AboutSourceMd from "@assets/markdown/about.md";
import PrivacySourceMd from "@assets/markdown/privacy.md";
import SecuritySourceMd from "@assets/markdown/security.md";

const MarkdownFiles = {
  privacy: PrivacySourceMd,
  about: AboutSourceMd,
  security: SecuritySourceMd,
};

/* eslint-disable */

// @autogenerated-begin

import abcde_criteria from "@assets/markdown/questions/abcde_criteria.md";
import delete_info from "@assets/markdown/questions/delete_info.md";
import take_from_gallery from "@assets/markdown/questions/take_from_gallery.md";
import take_photos from "@assets/markdown/questions/take_photos.md";
import use_app from "@assets/markdown/questions/use_app.md";

export const QuestionMarkdownFiles = {
    abcde_criteria,
    delete_info,
    take_from_gallery,
    take_photos,
    use_app,
};

// @autogenerated-end

/* eslint-enable */

export default MarkdownFiles;
