#!/usr/bin/env python

import os

TOP_TEMPLATE = """
// @autogenerated-begin

"""

MID_TEMPLATE = """

export const QuestionMarkdownFiles = {
"""

BOTTOM_TEMPLATE = """
};

// @autogenerated-end
"""


def main():
    path = os.getcwd()
    file = open(path + "/src/utils/markdowns.ts", "r", encoding="utf-8")
    file_txt = file.read()
    [prv_code, rem_code] = file_txt.split("\n// @autogenerated-begin\n")
    [_, nxt_code] = rem_code.split("// @autogenerated-end\n")
    dir_list = os.listdir(path + "/assets/markdown/questions")

    imports = []
    items = []

    for md_file in dir_list:
        name = md_file[:-3]
        imports.append(
            f'import {name} from "@assets/markdown/questions/{md_file}";')
        items.append(f'    {name},')

    imports_code = "\n".join(imports)
    items_code = "\n".join(items)

    generated_code = (
        TOP_TEMPLATE +
        imports_code +
        MID_TEMPLATE +
        items_code +
        BOTTOM_TEMPLATE
    )

    code = (
        prv_code +
        generated_code +
        nxt_code
    )

    file.close()

    file = open(path + "/src/utils/markdowns.ts", "w", encoding="utf-8")
    file.write(code)
    file.close()

    print("Generated markdowns.ts")


if __name__ == '__main__':
    main()
